### ISSUE TITLE
@Consumer POJO

### ISSUE THREAD

**Issue by ssljivic** [reactor/reactor-spring#28]
Is there a chance that @Consumer classes can be built without a need to inject a property of type EventBus? 

Right now @Consumer classes need to have a injected EventBus or the exception "Property or field 'eventBus' cannot be found on object of type..." is thrown.

It would be good to remove this dependency and allow writing POJO consumers with minimal dependencies on reactor.

Thanks

**Comment by jangalinski** [comment]
+1 first thing I stumbled upon when I looked into the samples ...

**Comment by jakubkulhan** [comment]
:+1:
